In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dfx=pd.read_csv("Diabetes_XTrain.csv")
dfy=pd.read_csv("Diabetes_YTrain.csv")

In [3]:
dfx


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              7      168             88             42      321  38.2   
1              8      110             76              0        0  27.8   
2              7      147             76              0        0  39.4   
3              2      100             66             20       90  32.9   
4              4      129             86             20      270  35.1   
..           ...      ...            ...            ...      ...   ...   
571            2      111             60              0        0  26.2   
572            7      187             68             39      304  37.7   
573            2      122             60             18      106  29.8   
574            4      154             72             29      126  31.3   
575            1       88             78             29       76  32.0   

     DiabetesPedigreeFunction  Age  
0                       0.787   40  
1                       0.237   58  
2                       0.257   43  
3                       0.867   28  
4                       0.231   23  
..                        ...  ...  
571                     0.343   23  
572                     0.254   41  
573                     0.717   22  
574                     0.338   37  
575                     0.365   29  

[576 rows x 8 columns]

In [4]:
dfy

Outcome
0          1
1          0
2          1
3          1
4          0
..       ...
571        0
572        1
573        0
574        0
575        0

[576 rows x 1 columns]

In [5]:
x=dfx.values
y=dfy.values

In [14]:
print(x[0][0])

7.0


In [7]:
y

array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
    

In [13]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

In [108]:
def knn(x,y,query):
    vals=[]
    m=x.shape[0]
    for i in range(m):
        d=dist(query,x[i])
        vals.append((d,y[i]))
        
    vals=sorted(vals)
    vals=vals[:15]
    vals=np.array(vals)
    vals=np.unique(vals[:,1],return_counts=True)
    i=vals[1].argmax()
    return vals[0][i]
        
        
    

In [109]:
a=knn(x,y,[6,160,88,42,321,38,0.786,39])
a

array([1])

In [110]:
test=pd.read_csv("Diabetes_Xtest.csv")
test.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            0      180             90             26       90  36.5   
1            2       93             64             32      160  38.0   
2            2      114             68             22        0  28.7   
3           13       76             60              0        0  32.8   
4            1       80             74             11       60  30.0   

   DiabetesPedigreeFunction  Age  
0                     0.314   35  
1                     0.674   23  
2                     0.092   25  
3                     0.180   41  
4                     0.527   22

In [111]:
test=test.values
test.shape

(192, 8)

In [112]:
m=test.shape[0]
Y=[]
for i in range(m):
    j=knn(x,y,test[i])
    Y.append(j)

In [113]:
Y


[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [114]:
df=pd.DataFrame(Y,columns=['Outcome'])
df.to_csv('output1.csv',index=False)

In [115]:
##ACCURACY OF THIS MODEL IS 77 PERCENT AS IT IS AN BRUTEFORCE APPROACH